### ISSUE TITLE
EMF在Ubuntu22.04 环境中编译失败

### ISSUE THREAD

**Issue by spencergotowork** [OpenCloudOS/EMF-ebpf-module-framework#1]
**环境:**

Ubuntu22.04: 5.15.0-53-generic
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu

**问题:**

使用make编译过程中出现如下的类似错误：

```
/opt/cs_course/emf-ebpf/lib/libbpf/linker.c:594: undefined reference to `elf_errmsg'
/usr/bin/ld: /opt/cs_course/emf-ebpf/lib/libbpf/linker.c:568: undefined reference to `elf_errmsg'
/usr/bin/ld: /opt/cs_course/emf-ebpf/lib/libbpf/linker.c:576: undefined reference to `elf_errmsg'
/usr/bin/ld: /opt/cs_course/emf-ebpf/lib/libbpf/linker.c:606: undefined reference to `elf_errmsg'
/usr/bin/ld: /opt/cs_course/emf-ebpf/lib/libbpf/linker.c:588: undefined reference to `elf_errmsg'
/usr/bin/ld: /opt/cs_course/emf-ebpf/sysroot/lib/libbpf.a(linker.o):/opt/cs_course/emf-ebpf/lib/libbpf/linker.c:614: more undefined references to `elf_errmsg' follow
```
libelf库未被链接
仔细观察后是Makefile第[53行](https://github.com/OpenCloudOS/EMF-ebpf-module-framework/blob/main/tools/bpftool/Makefile#L43)出现顺序错误

修正之后可以正常编译

**Comment by newcuit** [comment]
issue已经收到，后期，建议搭建虚拟机，在OpenCloudOS或者TencentOS上面编译。

因为，目前ebpf相关的代码特性是依赖内核版本的，后期再ubuntu上面测试，可能会有一些异常。

**Comment by spencergotowork** [comment]
> issue已经收到，后期，建议搭建虚拟机，在OpenCloudOS或者TencentOS上面编译。
> 
> 因为，目前ebpf相关的代码特性是依赖内核版本的，后期再ubuntu上面测试，可能会有一些异常。

了解了
